### ISSUE TITLE
To-Do's for Lighthouse

### ISSUE THREAD

**Issue by Prkr93** [Romeslayer/fitlit#38]
- [x] Images need alt attribute.
- [x] HTML needs a lang attribute.

Manual Checks:
- [x] Page has a logical tab order.
- [x] Interactive controls are keyboard focusable.
- [x] Interactive elements indicate their purpose and state.
- [ ] The user's focus is directed to new content added to the page.
- [ ] User's focus is not accidentally trapped in a region.
- [ ] Custom controls have associated labels.
- [ ] Custom controls have ARIA roles.
- [ ] Visual order on the page follows DOM order.
- [ ] Offscreen content is hidden from assistive technology.
- [ ] HTML5 landmark elements are used to improve navigation.
